# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/mnt/faststorage/alan/iDL_3d/py_code/core.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Core(object):
    def setupUi(self, Core):
        Core.setObjectName("Core")
        Core.resize(593, 473)
        self._central_widget = QtWidgets.QWidget(Core)
        self._central_widget.setObjectName("_central_widget")
        self._text_label_idl_gtvt = QtWidgets.QLabel(self._central_widget)
        self._text_label_idl_gtvt.setGeometry(QtCore.QRect(20, 170, 101, 15))
        self._text_label_idl_gtvt.setObjectName("_text_label_idl_gtvt")
        self._text_label_patient = QtWidgets.QLabel(self._central_widget)
        self._text_label_patient.setGeometry(QtCore.QRect(20, 70, 91, 15))
        self._text_label_patient.setObjectName("_text_label_patient")
        self._combox_idl_gtvt = QtWidgets.QComboBox(self._central_widget)
        self._combox_idl_gtvt.setGeometry(QtCore.QRect(70, 190, 141, 21))
        self._combox_idl_gtvt.setObjectName("_combox_idl_gtvt")
        self._combox_patient = QtWidgets.QComboBox(self._central_widget)
        self._combox_patient.setGeometry(QtCore.QRect(70, 90, 141, 21))
        self._combox_patient.setObjectName("_combox_patient")
        self._slider_bright_ct = QtWidgets.QSlider(self._central_widget)
        self._slider_bright_ct.setGeometry(QtCore.QRect(20, 369, 31, 22))
        self._slider_bright_ct.setOrientation(QtCore.Qt.Horizontal)
        self._slider_bright_ct.setObjectName("_slider_bright_ct")
        self._slider_contrast_ct = QtWidgets.QSlider(self._central_widget)
        self._slider_contrast_ct.setGeometry(QtCore.QRect(20, 419, 31, 22))
        self._slider_contrast_ct.setOrientation(QtCore.Qt.Horizontal)
        self._slider_contrast_ct.setObjectName("_slider_contrast_ct")
        self._text_label_bright = QtWidgets.QLabel(self._central_widget)
        self._text_label_bright.setGeometry(QtCore.QRect(20, 349, 64, 15))
        self._text_label_bright.setObjectName("_text_label_bright")
        self._text_label_contrast = QtWidgets.QLabel(self._central_widget)
        self._text_label_contrast.setGeometry(QtCore.QRect(20, 399, 52, 15))
        self._text_label_contrast.setObjectName("_text_label_contrast")
        self._btn_next_idl_gtvn = QtWidgets.QToolButton(self._central_widget)
        self._btn_next_idl_gtvn.setGeometry(QtCore.QRect(210, 240, 51, 21))
        self._btn_next_idl_gtvn.setObjectName("_btn_next_idl_gtvn")
        self._combox_idl_gtvn = QtWidgets.QComboBox(self._central_widget)
        self._combox_idl_gtvn.setGeometry(QtCore.QRect(70, 240, 141, 21))
        self._combox_idl_gtvn.setObjectName("_combox_idl_gtvn")
        self._text_label_idl_gtvn = QtWidgets.QLabel(self._central_widget)
        self._text_label_idl_gtvn.setGeometry(QtCore.QRect(20, 220, 104, 15))
        self._text_label_idl_gtvn.setObjectName("_text_label_idl_gtvn")
        self._btn_prev_idl_gtvn = QtWidgets.QToolButton(self._central_widget)
        self._btn_prev_idl_gtvn.setGeometry(QtCore.QRect(20, 240, 51, 21))
        self._btn_prev_idl_gtvn.setObjectName("_btn_prev_idl_gtvn")
        self._btn_prev_idl_gtvt = QtWidgets.QToolButton(self._central_widget)
        self._btn_prev_idl_gtvt.setGeometry(QtCore.QRect(20, 190, 51, 21))
        self._btn_prev_idl_gtvt.setObjectName("_btn_prev_idl_gtvt")
        self._btn_next_idl_gtvt = QtWidgets.QToolButton(self._central_widget)
        self._btn_next_idl_gtvt.setGeometry(QtCore.QRect(210, 190, 51, 21))
        self._btn_next_idl_gtvt.setObjectName("_btn_next_idl_gtvt")
        self._btn_prev_patient = QtWidgets.QToolButton(self._central_widget)
        self._btn_prev_patient.setGeometry(QtCore.QRect(20, 90, 51, 21))
        self._btn_prev_patient.setObjectName("_btn_prev_patient")
        self._btn_next_patient = QtWidgets.QToolButton(self._central_widget)
        self._btn_next_patient.setGeometry(QtCore.QRect(210, 90, 51, 21))
        self._btn_next_patient.setObjectName("_btn_next_patient")
        self._btn_prev_baseline = QtWidgets.QToolButton(self._central_widget)
        self._btn_prev_baseline.setGeometry(QtCore.QRect(20, 40, 51, 21))
        self._btn_prev_baseline.setObjectName("_btn_prev_baseline")
        self._btn_next_baseline = QtWidgets.QToolButton(self._central_widget)
        self._btn_next_baseline.setGeometry(QtCore.QRect(210, 40, 51, 21))
        self._btn_next_baseline.setObjectName("_btn_next_baseline")
        self._combox_baseline = QtWidgets.QComboBox(self._central_widget)
        self._combox_baseline.setGeometry(QtCore.QRect(70, 40, 141, 21))
        self._combox_baseline.setObjectName("_combox_baseline")
        self._text_label_baseline = QtWidgets.QLabel(self._central_widget)
        self._text_label_baseline.setGeometry(QtCore.QRect(20, 20, 99, 15))
        self._text_label_baseline.setObjectName("_text_label_baseline")
        self._progress_bar_idl = QtWidgets.QProgressBar(self._central_widget)
        self._progress_bar_idl.setGeometry(QtCore.QRect(300, 320, 241, 21))
        self._progress_bar_idl.setProperty("value", 24)
        self._progress_bar_idl.setObjectName("_progress_bar_idl")
        self._text_label_idl_progress = QtWidgets.QLabel(self._central_widget)
        self._text_label_idl_progress.setGeometry(QtCore.QRect(300, 300, 152, 15))
        self._text_label_idl_progress.setObjectName("_text_label_idl_progress")
        self._text_label_annotation_tools = QtWidgets.QLabel(self._central_widget)
        self._text_label_annotation_tools.setGeometry(QtCore.QRect(300, 150, 241, 16))
        self._text_label_annotation_tools.setObjectName("_text_label_annotation_tools")
        self._btn_pen = QtWidgets.QPushButton(self._central_widget)
        self._btn_pen.setGeometry(QtCore.QRect(300, 190, 51, 31))
        self._btn_pen.setText("")
        self._btn_pen.setObjectName("_btn_pen")
        self._btn_clear = QtWidgets.QPushButton(self._central_widget)
        self._btn_clear.setGeometry(QtCore.QRect(430, 190, 51, 31))
        self._btn_clear.setText("")
        self._btn_clear.setObjectName("_btn_clear")
        self._btn_confirm = QtWidgets.QPushButton(self._central_widget)
        self._btn_confirm.setGeometry(QtCore.QRect(490, 190, 51, 31))
        self._btn_confirm.setText("")
        self._btn_confirm.setObjectName("_btn_confirm")
        self._text_box_annotation_msg = QtWidgets.QTextEdit(self._central_widget)
        self._text_box_annotation_msg.setGeometry(QtCore.QRect(300, 380, 241, 61))
        self._text_box_annotation_msg.setObjectName("_text_box_annotation_msg")
        self._radio_btn_transverse = QtWidgets.QRadioButton(self._central_widget)
        self._radio_btn_transverse.setGeometry(QtCore.QRect(301, 40, 92, 21))
        self._radio_btn_transverse.setObjectName("_radio_btn_transverse")
        self._radio_btn_coronal = QtWidgets.QRadioButton(self._central_widget)
        self._radio_btn_coronal.setGeometry(QtCore.QRect(399, 40, 72, 21))
        self._radio_btn_coronal.setObjectName("_radio_btn_coronal")
        self._radio_btn_sagittal = QtWidgets.QRadioButton(self._central_widget)
        self._radio_btn_sagittal.setGeometry(QtCore.QRect(477, 40, 71, 21))
        self._radio_btn_sagittal.setObjectName("_radio_btn_sagittal")
        self._radio_btn_ct = QtWidgets.QRadioButton(self._central_widget)
        self._radio_btn_ct.setGeometry(QtCore.QRect(21, 321, 42, 21))
        self._radio_btn_ct.setObjectName("_radio_btn_ct")
        self._radio_btn_pt = QtWidgets.QRadioButton(self._central_widget)
        self._radio_btn_pt.setGeometry(QtCore.QRect(75, 321, 41, 21))
        self._radio_btn_pt.setObjectName("_radio_btn_pt")
        self._radio_btn_mr1 = QtWidgets.QRadioButton(self._central_widget)
        self._radio_btn_mr1.setGeometry(QtCore.QRect(128, 321, 63, 21))
        self._radio_btn_mr1.setObjectName("_radio_btn_mr1")
        self._radio_btn_mr2 = QtWidgets.QRadioButton(self._central_widget)
        self._radio_btn_mr2.setGeometry(QtCore.QRect(197, 321, 63, 21))
        self._radio_btn_mr2.setObjectName("_radio_btn_mr2")
        self._slider_zoom = QtWidgets.QSlider(self._central_widget)
        self._slider_zoom.setGeometry(QtCore.QRect(300, 100, 241, 22))
        self._slider_zoom.setOrientation(QtCore.Qt.Horizontal)
        self._slider_zoom.setObjectName("_slider_zoom")
        self._text_label_zoom = QtWidgets.QLabel(self._central_widget)
        self._text_label_zoom.setGeometry(QtCore.QRect(300, 80, 52, 15))
        self._text_label_zoom.setObjectName("_text_label_zoom")
        self._btn_next_idl_gtvs = QtWidgets.QToolButton(self._central_widget)
        self._btn_next_idl_gtvs.setGeometry(QtCore.QRect(210, 140, 51, 21))
        self._btn_next_idl_gtvs.setObjectName("_btn_next_idl_gtvs")
        self._combox_idl_gtvs = QtWidgets.QComboBox(self._central_widget)
        self._combox_idl_gtvs.setGeometry(QtCore.QRect(70, 140, 141, 21))
        self._combox_idl_gtvs.setObjectName("_combox_idl_gtvs")
        self._btn_prev_idl_gtvs = QtWidgets.QToolButton(self._central_widget)
        self._btn_prev_idl_gtvs.setGeometry(QtCore.QRect(20, 140, 51, 21))
        self._btn_prev_idl_gtvs.setObjectName("_btn_prev_idl_gtvs")
        self._text_label_idl_gtvs = QtWidgets.QLabel(self._central_widget)
        self._text_label_idl_gtvs.setGeometry(QtCore.QRect(20, 120, 103, 15))
        self._text_label_idl_gtvs.setObjectName("_text_label_idl_gtvs")
        self._slider_bright_pt = QtWidgets.QSlider(self._central_widget)
        self._slider_bright_pt.setGeometry(QtCore.QRect(80, 370, 31, 22))
        self._slider_bright_pt.setOrientation(QtCore.Qt.Horizontal)
        self._slider_bright_pt.setObjectName("_slider_bright_pt")
        self._slider_bright_mr1 = QtWidgets.QSlider(self._central_widget)
        self._slider_bright_mr1.setGeometry(QtCore.QRect(150, 370, 31, 22))
        self._slider_bright_mr1.setOrientation(QtCore.Qt.Horizontal)
        self._slider_bright_mr1.setObjectName("_slider_bright_mr1")
        self._slider_bright_mr2 = QtWidgets.QSlider(self._central_widget)
        self._slider_bright_mr2.setGeometry(QtCore.QRect(210, 370, 31, 22))
        self._slider_bright_mr2.setOrientation(QtCore.Qt.Horizontal)
        self._slider_bright_mr2.setObjectName("_slider_bright_mr2")
        self._slider_contrast_pt = QtWidgets.QSlider(self._central_widget)
        self._slider_contrast_pt.setGeometry(QtCore.QRect(80, 420, 31, 22))
        self._slider_contrast_pt.setOrientation(QtCore.Qt.Horizontal)
        self._slider_contrast_pt.setObjectName("_slider_contrast_pt")
        self._slider_contrast_mr1 = QtWidgets.QSlider(self._central_widget)
        self._slider_contrast_mr1.setGeometry(QtCore.QRect(150, 420, 31, 22))
        self._slider_contrast_mr1.setOrientation(QtCore.Qt.Horizontal)
        self._slider_contrast_mr1.setObjectName("_slider_contrast_mr1")
        self._slider_contrast_mr2 = QtWidgets.QSlider(self._central_widget)
        self._slider_contrast_mr2.setGeometry(QtCore.QRect(210, 420, 31, 22))
        self._slider_contrast_mr2.setOrientation(QtCore.Qt.Horizontal)
        self._slider_contrast_mr2.setObjectName("_slider_contrast_mr2")
        self._slider_pen_size = QtWidgets.QSlider(self._central_widget)
        self._slider_pen_size.setGeometry(QtCore.QRect(300, 250, 241, 22))
        self._slider_pen_size.setOrientation(QtCore.Qt.Horizontal)
        self._slider_pen_size.setObjectName("_slider_pen_size")
        self._text_label_pen_size = QtWidgets.QLabel(self._central_widget)
        self._text_label_pen_size.setGeometry(QtCore.QRect(300, 230, 52, 15))
        self._text_label_pen_size.setObjectName("_text_label_pen_size")
        self._btn_eraser = QtWidgets.QPushButton(self._central_widget)
        self._btn_eraser.setGeometry(QtCore.QRect(360, 190, 51, 31))
        self._btn_eraser.setText("")
        self._btn_eraser.setObjectName("_btn_eraser")
        self._text_label_bright_contrast = QtWidgets.QLabel(self._central_widget)
        self._text_label_bright_contrast.setGeometry(QtCore.QRect(20, 300, 141, 16))
        self._text_label_bright_contrast.setObjectName("_text_label_bright_contrast")
        self._text_label_plane = QtWidgets.QLabel(self._central_widget)
        self._text_label_plane.setGeometry(QtCore.QRect(300, 20, 121, 16))
        self._text_label_plane.setObjectName("_text_label_plane")
        self._radio_btn_draw_gtvn = QtWidgets.QRadioButton(self._central_widget)
        self._radio_btn_draw_gtvn.setGeometry(QtCore.QRect(400, 170, 101, 21))
        self._radio_btn_draw_gtvn.setObjectName("_radio_btn_draw_gtvn")
        self._radio_btn_draw_gtvt = QtWidgets.QRadioButton(self._central_widget)
        self._radio_btn_draw_gtvt.setGeometry(QtCore.QRect(300, 170, 91, 21))
        self._radio_btn_draw_gtvt.setObjectName("_radio_btn_draw_gtvt")
        Core.setCentralWidget(self._central_widget)

        self.retranslateUi(Core)
        QtCore.QMetaObject.connectSlotsByName(Core)

    def retranslateUi(self, Core):
        _translate = QtCore.QCoreApplication.translate
        Core.setWindowTitle(_translate("Core", "Interactive Learning Tool"))
        self._text_label_idl_gtvt.setText(_translate("Core", "Select iDL GTVt"))
        self._text_label_patient.setText(_translate("Core", "Select Patient"))
        self._text_label_bright.setText(_translate("Core", "Brightness"))
        self._text_label_contrast.setText(_translate("Core", "Contrast"))
        self._btn_next_idl_gtvn.setText(_translate("Core", "..."))
        self._text_label_idl_gtvn.setText(_translate("Core", "Select iDL GTVn"))
        self._btn_prev_idl_gtvn.setText(_translate("Core", "..."))
        self._btn_prev_idl_gtvt.setText(_translate("Core", "..."))
        self._btn_next_idl_gtvt.setText(_translate("Core", "..."))
        self._btn_prev_patient.setText(_translate("Core", "..."))
        self._btn_next_patient.setText(_translate("Core", "..."))
        self._btn_prev_baseline.setText(_translate("Core", "..."))
        self._btn_next_baseline.setText(_translate("Core", "..."))
        self._text_label_baseline.setText(_translate("Core", "Select Baseline"))
        self._text_label_idl_progress.setText(_translate("Core", "Retraining Progress"))
        self._text_label_annotation_tools.setText(_translate("Core", "Annotation Tools"))
        self._radio_btn_transverse.setText(_translate("Core", "Transverse"))
        self._radio_btn_coronal.setText(_translate("Core", "Coronal"))
        self._radio_btn_sagittal.setText(_translate("Core", "Sagittal"))
        self._radio_btn_ct.setText(_translate("Core", "CT"))
        self._radio_btn_pt.setText(_translate("Core", "PT"))
        self._radio_btn_mr1.setText(_translate("Core", "MR-T1"))
        self._radio_btn_mr2.setText(_translate("Core", "MR-T2"))
        self._text_label_zoom.setText(_translate("Core", "Zoom In"))
        self._btn_next_idl_gtvs.setText(_translate("Core", "..."))
        self._btn_prev_idl_gtvs.setText(_translate("Core", "..."))
        self._text_label_idl_gtvs.setText(_translate("Core", "Select iDL GTVs"))
        self._text_label_pen_size.setText(_translate("Core", "Pen Size"))
        self._text_label_bright_contrast.setText(_translate("Core", "Brightness&Contrast"))
        self._text_label_plane.setText(_translate("Core", "Anatomical Plane"))
        self._radio_btn_draw_gtvn.setText(_translate("Core", "Draw GTVn"))
        self._radio_btn_draw_gtvt.setText(_translate("Core", "Draw GTVt"))

