# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/mnt/faststorage/alan/iDL_3d/py_code/core.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Core(object):
    def setupUi(self, Core):
        Core.setObjectName("Core")
        Core.resize(593, 473)
        self._central_widget = QtWidgets.QWidget(Core)
        self._central_widget.setObjectName("_central_widget")
        self._img_qlabel_ct = QtWidgets.QLabel(self._central_widget)
        self._img_qlabel_ct.setGeometry(QtCore.QRect(40, 20, 71, 71))
        self._img_qlabel_ct.setObjectName("_img_qlabel_ct")
        self._img_qlabel_pt = QtWidgets.QLabel(self._central_widget)
        self._img_qlabel_pt.setGeometry(QtCore.QRect(150, 20, 71, 71))
        self._img_qlabel_pt.setObjectName("_img_qlabel_pt")
        self._img_qlabel_mrt1 = QtWidgets.QLabel(self._central_widget)
        self._img_qlabel_mrt1.setGeometry(QtCore.QRect(40, 110, 71, 71))
        self._img_qlabel_mrt1.setObjectName("_img_qlabel_mrt1")
        self._img_qlabel_mrt2 = QtWidgets.QLabel(self._central_widget)
        self._img_qlabel_mrt2.setGeometry(QtCore.QRect(150, 110, 71, 71))
        self._img_qlabel_mrt2.setObjectName("_img_qlabel_mrt2")
        self._text_label_idl_gtvt = QtWidgets.QLabel(self._central_widget)
        self._text_label_idl_gtvt.setGeometry(QtCore.QRect(20, 350, 101, 15))
        self._text_label_idl_gtvt.setObjectName("_text_label_idl_gtvt")
        self._text_label_patient = QtWidgets.QLabel(self._central_widget)
        self._text_label_patient.setGeometry(QtCore.QRect(20, 250, 91, 15))
        self._text_label_patient.setObjectName("_text_label_patient")
        self._combox_idl_gtvt = QtWidgets.QComboBox(self._central_widget)
        self._combox_idl_gtvt.setGeometry(QtCore.QRect(70, 370, 141, 21))
        self._combox_idl_gtvt.setObjectName("_combox_idl_gtvt")
        self._combox_patient = QtWidgets.QComboBox(self._central_widget)
        self._combox_patient.setGeometry(QtCore.QRect(70, 270, 141, 21))
        self._combox_patient.setObjectName("_combox_patient")
        self._slider_bright_ct = QtWidgets.QSlider(self._central_widget)
        self._slider_bright_ct.setGeometry(QtCore.QRect(300, 69, 31, 22))
        self._slider_bright_ct.setOrientation(QtCore.Qt.Horizontal)
        self._slider_bright_ct.setObjectName("_slider_bright_ct")
        self._slider_contrast_ct = QtWidgets.QSlider(self._central_widget)
        self._slider_contrast_ct.setGeometry(QtCore.QRect(300, 119, 31, 22))
        self._slider_contrast_ct.setOrientation(QtCore.Qt.Horizontal)
        self._slider_contrast_ct.setObjectName("_slider_contrast_ct")
        self._text_label_bright = QtWidgets.QLabel(self._central_widget)
        self._text_label_bright.setGeometry(QtCore.QRect(300, 49, 64, 15))
        self._text_label_bright.setObjectName("_text_label_bright")
        self._text_label_contrast = QtWidgets.QLabel(self._central_widget)
        self._text_label_contrast.setGeometry(QtCore.QRect(300, 99, 52, 15))
        self._text_label_contrast.setObjectName("_text_label_contrast")
        self._btn_next_idl_gtvn = QtWidgets.QToolButton(self._central_widget)
        self._btn_next_idl_gtvn.setGeometry(QtCore.QRect(210, 420, 51, 21))
        self._btn_next_idl_gtvn.setObjectName("_btn_next_idl_gtvn")
        self._combox_idl_gtvn = QtWidgets.QComboBox(self._central_widget)
        self._combox_idl_gtvn.setGeometry(QtCore.QRect(70, 420, 141, 21))
        self._combox_idl_gtvn.setObjectName("_combox_idl_gtvn")
        self._text_label_idl_gtvn = QtWidgets.QLabel(self._central_widget)
        self._text_label_idl_gtvn.setGeometry(QtCore.QRect(20, 400, 104, 15))
        self._text_label_idl_gtvn.setObjectName("_text_label_idl_gtvn")
        self._btn_prev_idl_gtvn = QtWidgets.QToolButton(self._central_widget)
        self._btn_prev_idl_gtvn.setGeometry(QtCore.QRect(20, 420, 51, 21))
        self._btn_prev_idl_gtvn.setObjectName("_btn_prev_idl_gtvn")
        self._btn_prev_idl_gtvt = QtWidgets.QToolButton(self._central_widget)
        self._btn_prev_idl_gtvt.setGeometry(QtCore.QRect(20, 370, 51, 21))
        self._btn_prev_idl_gtvt.setObjectName("_btn_prev_idl_gtvt")
        self._btn_next_idl_gtvt = QtWidgets.QToolButton(self._central_widget)
        self._btn_next_idl_gtvt.setGeometry(QtCore.QRect(210, 370, 51, 21))
        self._btn_next_idl_gtvt.setObjectName("_btn_next_idl_gtvt")
        self._btn_prev_patient = QtWidgets.QToolButton(self._central_widget)
        self._btn_prev_patient.setGeometry(QtCore.QRect(20, 270, 51, 21))
        self._btn_prev_patient.setObjectName("_btn_prev_patient")
        self._btn_next_patient = QtWidgets.QToolButton(self._central_widget)
        self._btn_next_patient.setGeometry(QtCore.QRect(210, 270, 51, 21))
        self._btn_next_patient.setObjectName("_btn_next_patient")
        self._btn_prev_baseline = QtWidgets.QToolButton(self._central_widget)
        self._btn_prev_baseline.setGeometry(QtCore.QRect(20, 220, 51, 21))
        self._btn_prev_baseline.setObjectName("_btn_prev_baseline")
        self._btn_next_baseline = QtWidgets.QToolButton(self._central_widget)
        self._btn_next_baseline.setGeometry(QtCore.QRect(210, 220, 51, 21))
        self._btn_next_baseline.setObjectName("_btn_next_baseline")
        self._combox_baseline = QtWidgets.QComboBox(self._central_widget)
        self._combox_baseline.setGeometry(QtCore.QRect(70, 220, 141, 21))
        self._combox_baseline.setObjectName("_combox_baseline")
        self._text_label_baseline = QtWidgets.QLabel(self._central_widget)
        self._text_label_baseline.setGeometry(QtCore.QRect(20, 200, 99, 15))
        self._text_label_baseline.setObjectName("_text_label_baseline")
        self._progress_bar_idl = QtWidgets.QProgressBar(self._central_widget)
        self._progress_bar_idl.setGeometry(QtCore.QRect(300, 360, 241, 21))
        self._progress_bar_idl.setProperty("value", 24)
        self._progress_bar_idl.setObjectName("_progress_bar_idl")
        self._text_label_idl_progress = QtWidgets.QLabel(self._central_widget)
        self._text_label_idl_progress.setGeometry(QtCore.QRect(300, 340, 152, 15))
        self._text_label_idl_progress.setObjectName("_text_label_idl_progress")
        self._text_label_annotation_tools = QtWidgets.QLabel(self._central_widget)
        self._text_label_annotation_tools.setGeometry(QtCore.QRect(300, 230, 241, 16))
        self._text_label_annotation_tools.setObjectName("_text_label_annotation_tools")
        self._btn_pen = QtWidgets.QPushButton(self._central_widget)
        self._btn_pen.setGeometry(QtCore.QRect(300, 250, 51, 31))
        self._btn_pen.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../../mnt/faststorage/alan/iDL_3d/icons/icon_pen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self._btn_pen.setIcon(icon)
        self._btn_pen.setObjectName("_btn_pen")
        self._btn_eraser = QtWidgets.QPushButton(self._central_widget)
        self._btn_eraser.setGeometry(QtCore.QRect(360, 250, 51, 31))
        self._btn_eraser.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../../../../mnt/faststorage/alan/iDL_3d/icons/icon_eraser.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self._btn_eraser.setIcon(icon1)
        self._btn_eraser.setObjectName("_btn_eraser")
        self._btn_clear = QtWidgets.QPushButton(self._central_widget)
        self._btn_clear.setGeometry(QtCore.QRect(430, 250, 51, 31))
        self._btn_clear.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../../../../../mnt/faststorage/alan/iDL_3d/icons/icon_clear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self._btn_clear.setIcon(icon2)
        self._btn_clear.setObjectName("_btn_clear")
        self._btn_confirm = QtWidgets.QPushButton(self._central_widget)
        self._btn_confirm.setGeometry(QtCore.QRect(490, 250, 51, 31))
        self._btn_confirm.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../../../../../mnt/faststorage/alan/iDL_3d/icons/icon_confirm.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self._btn_confirm.setIcon(icon3)
        self._btn_confirm.setObjectName("_btn_confirm")
        self._text_box_annotation_msg = QtWidgets.QTextEdit(self._central_widget)
        self._text_box_annotation_msg.setGeometry(QtCore.QRect(300, 390, 241, 61))
        self._text_box_annotation_msg.setObjectName("_text_box_annotation_msg")
        self._radio_btn_transverse = QtWidgets.QRadioButton(self._central_widget)
        self._radio_btn_transverse.setGeometry(QtCore.QRect(301, 150, 92, 21))
        self._radio_btn_transverse.setObjectName("_radio_btn_transverse")
        self._radio_btn_coronal = QtWidgets.QRadioButton(self._central_widget)
        self._radio_btn_coronal.setGeometry(QtCore.QRect(399, 150, 72, 21))
        self._radio_btn_coronal.setObjectName("_radio_btn_coronal")
        self._radio_btn_sagittal = QtWidgets.QRadioButton(self._central_widget)
        self._radio_btn_sagittal.setGeometry(QtCore.QRect(477, 150, 71, 21))
        self._radio_btn_sagittal.setObjectName("_radio_btn_sagittal")
        self._radio_btn_ct = QtWidgets.QRadioButton(self._central_widget)
        self._radio_btn_ct.setGeometry(QtCore.QRect(301, 21, 42, 21))
        self._radio_btn_ct.setObjectName("_radio_btn_ct")
        self._radio_btn_pt = QtWidgets.QRadioButton(self._central_widget)
        self._radio_btn_pt.setGeometry(QtCore.QRect(355, 21, 41, 21))
        self._radio_btn_pt.setObjectName("_radio_btn_pt")
        self._radio_btn_mrt1 = QtWidgets.QRadioButton(self._central_widget)
        self._radio_btn_mrt1.setGeometry(QtCore.QRect(408, 21, 63, 21))
        self._radio_btn_mrt1.setObjectName("_radio_btn_mrt1")
        self._radio_btn_mrt2 = QtWidgets.QRadioButton(self._central_widget)
        self._radio_btn_mrt2.setGeometry(QtCore.QRect(477, 21, 63, 21))
        self._radio_btn_mrt2.setObjectName("_radio_btn_mrt2")
        self._slider_zoom = QtWidgets.QSlider(self._central_widget)
        self._slider_zoom.setGeometry(QtCore.QRect(300, 200, 241, 22))
        self._slider_zoom.setOrientation(QtCore.Qt.Horizontal)
        self._slider_zoom.setObjectName("_slider_zoom")
        self._text_label_zoom = QtWidgets.QLabel(self._central_widget)
        self._text_label_zoom.setGeometry(QtCore.QRect(300, 180, 52, 15))
        self._text_label_zoom.setObjectName("_text_label_zoom")
        self._btn_next_idl_gtvs = QtWidgets.QToolButton(self._central_widget)
        self._btn_next_idl_gtvs.setGeometry(QtCore.QRect(210, 320, 51, 21))
        self._btn_next_idl_gtvs.setObjectName("_btn_next_idl_gtvs")
        self._combox_idl_gtvs = QtWidgets.QComboBox(self._central_widget)
        self._combox_idl_gtvs.setGeometry(QtCore.QRect(70, 320, 141, 21))
        self._combox_idl_gtvs.setObjectName("_combox_idl_gtvs")
        self._btn_prev_idl_gtvs = QtWidgets.QToolButton(self._central_widget)
        self._btn_prev_idl_gtvs.setGeometry(QtCore.QRect(20, 320, 51, 21))
        self._btn_prev_idl_gtvs.setObjectName("_btn_prev_idl_gtvs")
        self._text_label_idl_gtvs = QtWidgets.QLabel(self._central_widget)
        self._text_label_idl_gtvs.setGeometry(QtCore.QRect(20, 300, 103, 15))
        self._text_label_idl_gtvs.setObjectName("_text_label_idl_gtvs")
        self._slider_bright_pt = QtWidgets.QSlider(self._central_widget)
        self._slider_bright_pt.setGeometry(QtCore.QRect(360, 70, 31, 22))
        self._slider_bright_pt.setOrientation(QtCore.Qt.Horizontal)
        self._slider_bright_pt.setObjectName("_slider_bright_pt")
        self._slider_bright_mrt1 = QtWidgets.QSlider(self._central_widget)
        self._slider_bright_mrt1.setGeometry(QtCore.QRect(430, 70, 31, 22))
        self._slider_bright_mrt1.setOrientation(QtCore.Qt.Horizontal)
        self._slider_bright_mrt1.setObjectName("_slider_bright_mrt1")
        self._slider_bright_mrt2 = QtWidgets.QSlider(self._central_widget)
        self._slider_bright_mrt2.setGeometry(QtCore.QRect(490, 70, 31, 22))
        self._slider_bright_mrt2.setOrientation(QtCore.Qt.Horizontal)
        self._slider_bright_mrt2.setObjectName("_slider_bright_mrt2")
        self._slider_contrast_pt = QtWidgets.QSlider(self._central_widget)
        self._slider_contrast_pt.setGeometry(QtCore.QRect(360, 120, 31, 22))
        self._slider_contrast_pt.setOrientation(QtCore.Qt.Horizontal)
        self._slider_contrast_pt.setObjectName("_slider_contrast_pt")
        self._slider_contrast_mrt1 = QtWidgets.QSlider(self._central_widget)
        self._slider_contrast_mrt1.setGeometry(QtCore.QRect(430, 120, 31, 22))
        self._slider_contrast_mrt1.setOrientation(QtCore.Qt.Horizontal)
        self._slider_contrast_mrt1.setObjectName("_slider_contrast_mrt1")
        self._slider_contrast_mrt2 = QtWidgets.QSlider(self._central_widget)
        self._slider_contrast_mrt2.setGeometry(QtCore.QRect(490, 120, 31, 22))
        self._slider_contrast_mrt2.setOrientation(QtCore.Qt.Horizontal)
        self._slider_contrast_mrt2.setObjectName("_slider_contrast_mrt2")
        self._slider_pen_size = QtWidgets.QSlider(self._central_widget)
        self._slider_pen_size.setGeometry(QtCore.QRect(300, 310, 241, 22))
        self._slider_pen_size.setOrientation(QtCore.Qt.Horizontal)
        self._slider_pen_size.setObjectName("_slider_pen_size")
        self._text_label_pen_size = QtWidgets.QLabel(self._central_widget)
        self._text_label_pen_size.setGeometry(QtCore.QRect(300, 290, 52, 15))
        self._text_label_pen_size.setObjectName("_text_label_pen_size")
        Core.setCentralWidget(self._central_widget)

        self.retranslateUi(Core)
        QtCore.QMetaObject.connectSlotsByName(Core)

    def retranslateUi(self, Core):
        _translate = QtCore.QCoreApplication.translate
        Core.setWindowTitle(_translate("Core", "Interactive Learning Tool"))
        self._img_qlabel_ct.setText(_translate("Core", "ct_img"))
        self._img_qlabel_pt.setText(_translate("Core", "pt_img"))
        self._img_qlabel_mrt1.setText(_translate("Core", "mrt1_img"))
        self._img_qlabel_mrt2.setText(_translate("Core", "mrt2_img"))
        self._text_label_idl_gtvt.setText(_translate("Core", "Choose iDL GTVt"))
        self._text_label_patient.setText(_translate("Core", "Choose Patient"))
        self._text_label_bright.setText(_translate("Core", "Brightness"))
        self._text_label_contrast.setText(_translate("Core", "Contrast"))
        self._btn_next_idl_gtvn.setText(_translate("Core", "..."))
        self._text_label_idl_gtvn.setText(_translate("Core", "Choose iDL GTVn"))
        self._btn_prev_idl_gtvn.setText(_translate("Core", "..."))
        self._btn_prev_idl_gtvt.setText(_translate("Core", "..."))
        self._btn_next_idl_gtvt.setText(_translate("Core", "..."))
        self._btn_prev_patient.setText(_translate("Core", "..."))
        self._btn_next_patient.setText(_translate("Core", "..."))
        self._btn_prev_baseline.setText(_translate("Core", "..."))
        self._btn_next_baseline.setText(_translate("Core", "..."))
        self._text_label_baseline.setText(_translate("Core", "Choose Baseline"))
        self._text_label_idl_progress.setText(_translate("Core", "Retraining Progress"))
        self._text_label_annotation_tools.setText(_translate("Core", "Annotation Tools"))
        self._radio_btn_transverse.setText(_translate("Core", "Transverse"))
        self._radio_btn_coronal.setText(_translate("Core", "Coronal"))
        self._radio_btn_sagittal.setText(_translate("Core", "Sagittal"))
        self._radio_btn_ct.setText(_translate("Core", "CT"))
        self._radio_btn_pt.setText(_translate("Core", "PT"))
        self._radio_btn_mrt1.setText(_translate("Core", "MR-T1"))
        self._radio_btn_mrt2.setText(_translate("Core", "MR-T2"))
        self._text_label_zoom.setText(_translate("Core", "Zoom In"))
        self._btn_next_idl_gtvs.setText(_translate("Core", "..."))
        self._btn_prev_idl_gtvs.setText(_translate("Core", "..."))
        self._text_label_idl_gtvs.setText(_translate("Core", "Choose iDL GTVs"))
        self._text_label_pen_size.setText(_translate("Core", "Pen Size"))

