# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/alan/alan/iDL_3d/py_code/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(593, 673)
        self._central_widget = QtWidgets.QWidget(MainWindow)
        self._central_widget.setObjectName("_central_widget")
        self._display_frame_ct = QtWidgets.QLabel(self._central_widget)
        self._display_frame_ct.setGeometry(QtCore.QRect(50, 10, 41, 81))
        self._display_frame_ct.setObjectName("_display_frame_ct")
        self._display_frame_pt = QtWidgets.QLabel(self._central_widget)
        self._display_frame_pt.setGeometry(QtCore.QRect(150, 20, 81, 71))
        self._display_frame_pt.setObjectName("_display_frame_pt")
        self._display_frame_mrt1 = QtWidgets.QLabel(self._central_widget)
        self._display_frame_mrt1.setGeometry(QtCore.QRect(40, 110, 71, 71))
        self._display_frame_mrt1.setObjectName("_display_frame_mrt1")
        self._display_frame_mrt2 = QtWidgets.QLabel(self._central_widget)
        self._display_frame_mrt2.setGeometry(QtCore.QRect(160, 120, 71, 61))
        self._display_frame_mrt2.setObjectName("_display_frame_mrt2")
        self._text_label_idl_gtvt = QtWidgets.QLabel(self._central_widget)
        self._text_label_idl_gtvt.setGeometry(QtCore.QRect(300, 100, 101, 15))
        self._text_label_idl_gtvt.setObjectName("_text_label_idl_gtvt")
        self._text_label_patient = QtWidgets.QLabel(self._central_widget)
        self._text_label_patient.setGeometry(QtCore.QRect(300, 200, 91, 15))
        self._text_label_patient.setObjectName("_text_label_patient")
        self._text_label_round = QtWidgets.QLabel(self._central_widget)
        self._text_label_round.setGeometry(QtCore.QRect(300, 250, 87, 15))
        self._text_label_round.setObjectName("_text_label_round")
        self._combox_idl_gtvt = QtWidgets.QComboBox(self._central_widget)
        self._combox_idl_gtvt.setGeometry(QtCore.QRect(350, 120, 141, 21))
        self._combox_idl_gtvt.setObjectName("_combox_idl_gtvt")
        self._combox_patient = QtWidgets.QComboBox(self._central_widget)
        self._combox_patient.setGeometry(QtCore.QRect(350, 220, 141, 21))
        self._combox_patient.setObjectName("_combox_patient")
        self._btn_prev_round = QtWidgets.QToolButton(self._central_widget)
        self._btn_prev_round.setGeometry(QtCore.QRect(300, 270, 51, 21))
        self._btn_prev_round.setObjectName("_btn_prev_round")
        self._btn_next_round = QtWidgets.QToolButton(self._central_widget)
        self._btn_next_round.setGeometry(QtCore.QRect(490, 270, 51, 21))
        self._btn_next_round.setObjectName("_btn_next_round")
        self._combox_round = QtWidgets.QComboBox(self._central_widget)
        self._combox_round.setGeometry(QtCore.QRect(350, 270, 141, 21))
        self._combox_round.setObjectName("_combox_round")
        self._slider_bright = QtWidgets.QSlider(self._central_widget)
        self._slider_bright.setGeometry(QtCore.QRect(300, 359, 241, 22))
        self._slider_bright.setOrientation(QtCore.Qt.Horizontal)
        self._slider_bright.setObjectName("_slider_bright")
        self._slider_contrast = QtWidgets.QSlider(self._central_widget)
        self._slider_contrast.setGeometry(QtCore.QRect(300, 409, 241, 22))
        self._slider_contrast.setOrientation(QtCore.Qt.Horizontal)
        self._slider_contrast.setObjectName("_slider_contrast")
        self._text_label_bright = QtWidgets.QLabel(self._central_widget)
        self._text_label_bright.setGeometry(QtCore.QRect(300, 339, 64, 15))
        self._text_label_bright.setObjectName("_text_label_bright")
        self._text_label_contrast = QtWidgets.QLabel(self._central_widget)
        self._text_label_contrast.setGeometry(QtCore.QRect(300, 389, 52, 15))
        self._text_label_contrast.setObjectName("_text_label_contrast")
        self._btn_next_idl_gtvn = QtWidgets.QToolButton(self._central_widget)
        self._btn_next_idl_gtvn.setGeometry(QtCore.QRect(490, 170, 51, 21))
        self._btn_next_idl_gtvn.setObjectName("_btn_next_idl_gtvn")
        self._combox_idl_gtvn = QtWidgets.QComboBox(self._central_widget)
        self._combox_idl_gtvn.setGeometry(QtCore.QRect(350, 170, 141, 21))
        self._combox_idl_gtvn.setObjectName("_combox_idl_gtvn")
        self._text_label_idl_gtvn = QtWidgets.QLabel(self._central_widget)
        self._text_label_idl_gtvn.setGeometry(QtCore.QRect(300, 150, 104, 15))
        self._text_label_idl_gtvn.setObjectName("_text_label_idl_gtvn")
        self._btn_prev_idl_gtvn = QtWidgets.QToolButton(self._central_widget)
        self._btn_prev_idl_gtvn.setGeometry(QtCore.QRect(300, 170, 51, 21))
        self._btn_prev_idl_gtvn.setObjectName("_btn_prev_idl_gtvn")
        self._btn_prev_idl_gtvt = QtWidgets.QToolButton(self._central_widget)
        self._btn_prev_idl_gtvt.setGeometry(QtCore.QRect(300, 120, 51, 21))
        self._btn_prev_idl_gtvt.setObjectName("_btn_prev_idl_gtvt")
        self._btn_next_idl_gtvt = QtWidgets.QToolButton(self._central_widget)
        self._btn_next_idl_gtvt.setGeometry(QtCore.QRect(490, 120, 51, 21))
        self._btn_next_idl_gtvt.setObjectName("_btn_next_idl_gtvt")
        self._btn_prev_patient = QtWidgets.QToolButton(self._central_widget)
        self._btn_prev_patient.setGeometry(QtCore.QRect(300, 220, 51, 21))
        self._btn_prev_patient.setObjectName("_btn_prev_patient")
        self._btn_next_patient = QtWidgets.QToolButton(self._central_widget)
        self._btn_next_patient.setGeometry(QtCore.QRect(490, 220, 51, 21))
        self._btn_next_patient.setObjectName("_btn_next_patient")
        self._btn_prev_baseline = QtWidgets.QToolButton(self._central_widget)
        self._btn_prev_baseline.setGeometry(QtCore.QRect(300, 20, 51, 21))
        self._btn_prev_baseline.setObjectName("_btn_prev_baseline")
        self._btn_next_baseline = QtWidgets.QToolButton(self._central_widget)
        self._btn_next_baseline.setGeometry(QtCore.QRect(490, 20, 51, 21))
        self._btn_next_baseline.setObjectName("_btn_next_baseline")
        self._combox_baseline = QtWidgets.QComboBox(self._central_widget)
        self._combox_baseline.setGeometry(QtCore.QRect(350, 20, 141, 21))
        self._combox_baseline.setObjectName("_combox_baseline")
        self._text_label_baseline = QtWidgets.QLabel(self._central_widget)
        self._text_label_baseline.setGeometry(QtCore.QRect(300, 0, 99, 15))
        self._text_label_baseline.setObjectName("_text_label_baseline")
        self._progress_bar_idl_gtvt = QtWidgets.QProgressBar(self._central_widget)
        self._progress_bar_idl_gtvt.setGeometry(QtCore.QRect(300, 620, 241, 21))
        self._progress_bar_idl_gtvt.setProperty("value", 24)
        self._progress_bar_idl_gtvt.setObjectName("_progress_bar_idl_gtvt")
        self._text_label_idl_gtvt_progress = QtWidgets.QLabel(self._central_widget)
        self._text_label_idl_gtvt_progress.setGeometry(QtCore.QRect(300, 600, 152, 15))
        self._text_label_idl_gtvt_progress.setObjectName(
            "_text_label_idl_gtvt_progress"
        )
        self._text_label_annotation_tools = QtWidgets.QLabel(self._central_widget)
        self._text_label_annotation_tools.setGeometry(QtCore.QRect(300, 540, 241, 16))
        self._text_label_annotation_tools.setObjectName("_text_label_annotation_tools")
        self._btn_pen = QtWidgets.QPushButton(self._central_widget)
        self._btn_pen.setGeometry(QtCore.QRect(300, 560, 51, 31))
        self._btn_pen.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap(
                "../../../../../../mnt/faststorage/alan/iDL_3d/icons/icon_pen.png"
            ),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self._btn_pen.setIcon(icon)
        self._btn_pen.setObjectName("_btn_pen")
        self._btn_eraser = QtWidgets.QPushButton(self._central_widget)
        self._btn_eraser.setGeometry(QtCore.QRect(360, 560, 51, 31))
        self._btn_eraser.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(
            QtGui.QPixmap(
                "../../../../../../mnt/faststorage/alan/iDL_3d/icons/icon_eraser.png"
            ),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self._btn_eraser.setIcon(icon1)
        self._btn_eraser.setObjectName("_btn_eraser")
        self._btn_clear = QtWidgets.QPushButton(self._central_widget)
        self._btn_clear.setGeometry(QtCore.QRect(430, 560, 51, 31))
        self._btn_clear.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(
            QtGui.QPixmap(
                "../../../../../../mnt/faststorage/alan/iDL_3d/icons/icon_clear.png"
            ),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self._btn_clear.setIcon(icon2)
        self._btn_clear.setObjectName("_btn_clear")
        self._btn_confirm = QtWidgets.QPushButton(self._central_widget)
        self._btn_confirm.setGeometry(QtCore.QRect(490, 560, 51, 31))
        self._btn_confirm.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(
            QtGui.QPixmap(
                "../../../../../../mnt/faststorage/alan/iDL_3d/icons/icon-confirm.png"
            ),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self._btn_confirm.setIcon(icon3)
        self._btn_confirm.setObjectName("_btn_confirm")
        self._text_box_annotation_msg = QtWidgets.QTextEdit(self._central_widget)
        self._text_box_annotation_msg.setGeometry(QtCore.QRect(300, 519, 241, 21))
        self._text_box_annotation_msg.setObjectName("_text_box_annotation_msg")
        self._radio_btn_transverse = QtWidgets.QRadioButton(self._central_widget)
        self._radio_btn_transverse.setGeometry(QtCore.QRect(301, 440, 92, 21))
        self._radio_btn_transverse.setObjectName("_radio_btn_transverse")
        self._radio_btn_coronal = QtWidgets.QRadioButton(self._central_widget)
        self._radio_btn_coronal.setGeometry(QtCore.QRect(399, 440, 72, 21))
        self._radio_btn_coronal.setObjectName("_radio_btn_coronal")
        self._radio_btn_sagittal = QtWidgets.QRadioButton(self._central_widget)
        self._radio_btn_sagittal.setGeometry(QtCore.QRect(477, 440, 71, 21))
        self._radio_btn_sagittal.setObjectName("_radio_btn_sagittal")
        self._radio_btn_ct = QtWidgets.QRadioButton(self._central_widget)
        self._radio_btn_ct.setGeometry(QtCore.QRect(301, 311, 42, 21))
        self._radio_btn_ct.setObjectName("_radio_btn_ct")
        self._radio_btn_pt = QtWidgets.QRadioButton(self._central_widget)
        self._radio_btn_pt.setGeometry(QtCore.QRect(355, 311, 41, 21))
        self._radio_btn_pt.setObjectName("_radio_btn_pt")
        self._radio_btn_mrt1 = QtWidgets.QRadioButton(self._central_widget)
        self._radio_btn_mrt1.setGeometry(QtCore.QRect(408, 311, 63, 21))
        self._radio_btn_mrt1.setObjectName("_radio_btn_mrt1")
        self._radio_btn_mrt2 = QtWidgets.QRadioButton(self._central_widget)
        self._radio_btn_mrt2.setGeometry(QtCore.QRect(477, 311, 63, 21))
        self._radio_btn_mrt2.setObjectName("_radio_btn_mrt2")
        self._slider_zoom = QtWidgets.QSlider(self._central_widget)
        self._slider_zoom.setGeometry(QtCore.QRect(300, 490, 241, 22))
        self._slider_zoom.setOrientation(QtCore.Qt.Horizontal)
        self._slider_zoom.setObjectName("_slider_zoom")
        self._text_label_zoom = QtWidgets.QLabel(self._central_widget)
        self._text_label_zoom.setGeometry(QtCore.QRect(300, 470, 52, 15))
        self._text_label_zoom.setObjectName("_text_label_zoom")
        self._btn_next_idl_gtvs = QtWidgets.QToolButton(self._central_widget)
        self._btn_next_idl_gtvs.setGeometry(QtCore.QRect(490, 70, 51, 21))
        self._btn_next_idl_gtvs.setObjectName("_btn_next_idl_gtvs")
        self._combox_idl_gtvs = QtWidgets.QComboBox(self._central_widget)
        self._combox_idl_gtvs.setGeometry(QtCore.QRect(350, 70, 141, 21))
        self._combox_idl_gtvs.setObjectName("_combox_idl_gtvs")
        self._btn_prev_idl_gtvs = QtWidgets.QToolButton(self._central_widget)
        self._btn_prev_idl_gtvs.setGeometry(QtCore.QRect(300, 70, 51, 21))
        self._btn_prev_idl_gtvs.setObjectName("_btn_prev_idl_gtvs")
        self._text_label_idl_gtvs = QtWidgets.QLabel(self._central_widget)
        self._text_label_idl_gtvs.setGeometry(QtCore.QRect(300, 50, 103, 15))
        self._text_label_idl_gtvs.setObjectName("_text_label_idl_gtvs")
        MainWindow.setCentralWidget(self._central_widget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Interactive Learning Tool"))
        self._display_frame_ct.setText(_translate("MainWindow", "ct_img"))
        self._display_frame_pt.setText(_translate("MainWindow", "pt_img"))
        self._display_frame_mrt1.setText(_translate("MainWindow", "mrt1_img"))
        self._display_frame_mrt2.setText(_translate("MainWindow", "mrt2_img"))
        self._text_label_idl_gtvt.setText(_translate("MainWindow", "Choose iDL GTVt"))
        self._text_label_patient.setText(_translate("MainWindow", "Choose Patient"))
        self._text_label_round.setText(_translate("MainWindow", "Choose Round"))
        self._btn_prev_round.setText(_translate("MainWindow", "..."))
        self._btn_next_round.setText(_translate("MainWindow", "..."))
        self._text_label_bright.setText(_translate("MainWindow", "Brightness"))
        self._text_label_contrast.setText(_translate("MainWindow", "Contrast"))
        self._btn_next_idl_gtvn.setText(_translate("MainWindow", "..."))
        self._text_label_idl_gtvn.setText(_translate("MainWindow", "Choose iDL GTVn"))
        self._btn_prev_idl_gtvn.setText(_translate("MainWindow", "..."))
        self._btn_prev_idl_gtvt.setText(_translate("MainWindow", "..."))
        self._btn_next_idl_gtvt.setText(_translate("MainWindow", "..."))
        self._btn_prev_patient.setText(_translate("MainWindow", "..."))
        self._btn_next_patient.setText(_translate("MainWindow", "..."))
        self._btn_prev_baseline.setText(_translate("MainWindow", "..."))
        self._btn_next_baseline.setText(_translate("MainWindow", "..."))
        self._text_label_baseline.setText(_translate("MainWindow", "Choose Baseline"))
        self._text_label_idl_gtvt_progress.setText(
            _translate("MainWindow", "GTVt Retraining Progress")
        )
        self._text_label_annotation_tools.setText(
            _translate("MainWindow", "Annotation Tools")
        )
        self._radio_btn_transverse.setText(_translate("MainWindow", "Transverse"))
        self._radio_btn_coronal.setText(_translate("MainWindow", "Coronal"))
        self._radio_btn_sagittal.setText(_translate("MainWindow", "Sagittal"))
        self._radio_btn_ct.setText(_translate("MainWindow", "CT"))
        self._radio_btn_pt.setText(_translate("MainWindow", "PT"))
        self._radio_btn_mrt1.setText(_translate("MainWindow", "MR-T1"))
        self._radio_btn_mrt2.setText(_translate("MainWindow", "MR-T2"))
        self._text_label_zoom.setText(_translate("MainWindow", "Zoom In"))
        self._btn_next_idl_gtvs.setText(_translate("MainWindow", "..."))
        self._btn_prev_idl_gtvs.setText(_translate("MainWindow", "..."))
        self._text_label_idl_gtvs.setText(_translate("MainWindow", "Choose iDL GTVs"))
